# version: 2
# updates:
#   - package-ecosystem: gomod
#     directory: /
#     schedule:
#       interval: weekly
#       day: monday
#     open-pull-requests-limit: 10
#     labels:
#       - dependencies
#     groups:
#       kubernetes:
#         patterns:
#           - "k8s.io/*"
#           - "sigs.k8s.io/*"

#   - package-ecosystem: docker
#     directory: /
#     schedule:
#       interval: weekly
#       day: monday
#     labels:
#       - dependencies

#   - package-ecosystem: github-actions
#     directory: /
#     schedule:
#       interval: weekly
#       day: monday
#     labels:
#       - dependencies
