/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TokenUsage records the number of tokens consumed by a single step or the whole pipeline.
type TokenUsage struct {
	// InputTokens is the total number of prompt/input tokens sent to the LLM.
	InputTokens int64 `json:"inputTokens"`
	// OutputTokens is the total number of completion/output tokens generated by the LLM.
	OutputTokens int64 `json:"outputTokens"`
	// TotalTokens is InputTokens + OutputTokens, provided for convenient display.
	TotalTokens int64 `json:"totalTokens"`
}

// ArkFlowStepPhase describes the execution state of a single pipeline step.
// +kubebuilder:validation:Enum=Pending;Running;Succeeded;Failed;Skipped
type ArkFlowStepPhase string

const (
	ArkFlowStepPhasePending   ArkFlowStepPhase = "Pending"
	ArkFlowStepPhaseRunning   ArkFlowStepPhase = "Running"
	ArkFlowStepPhaseSucceeded ArkFlowStepPhase = "Succeeded"
	ArkFlowStepPhaseFailed    ArkFlowStepPhase = "Failed"
	// ArkFlowStepPhaseSkipped means the step was bypassed because its If condition evaluated to false.
	ArkFlowStepPhaseSkipped ArkFlowStepPhase = "Skipped"
)

// LoopSpec defines loop behaviour for a pipeline step.
type LoopSpec struct {
	// Condition is a Go template expression evaluated after each iteration.
	// The step repeats while this evaluates to a truthy value ("true", non-empty, non-"false", non-"0").
	// Example: "{{ gt (len .steps.collect.output) 0 }}"
	// +kubebuilder:validation:Required
	Condition string `json:"condition"`

	// MaxIterations caps the number of loop repetitions to prevent infinite loops.
	// +kubebuilder:default=10
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=100
	MaxIterations int `json:"maxIterations,omitempty"`
}

// ArkFlowPhase describes the overall execution state of the pipeline.
// +kubebuilder:validation:Enum=Pending;Running;Succeeded;Failed
type ArkFlowPhase string

const (
	ArkFlowPhasePending   ArkFlowPhase = "Pending"
	ArkFlowPhaseRunning   ArkFlowPhase = "Running"
	ArkFlowPhaseSucceeded ArkFlowPhase = "Succeeded"
	ArkFlowPhaseFailed    ArkFlowPhase = "Failed"
)

// ArkFlowStep defines one node in the agent DAG.
type ArkFlowStep struct {
	// Name is the unique identifier for this step within the pipeline.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// ArkAgent is the name of the ArkAgent that executes this step.
	// +kubebuilder:validation:Required
	ArkAgent string `json:"arkAgent"`

	// Inputs is a map of input key → Go template expression referencing pipeline
	// inputs or earlier step outputs. Example: "{{ .steps.research.output }}"
	Inputs map[string]string `json:"inputs,omitempty"`

	// DependsOn lists step names that must complete before this step runs.
	DependsOn []string `json:"dependsOn,omitempty"`

	// OutputSchema is an optional JSON Schema string that constrains this step's output.
	// When set, the schema is appended to the agent prompt and the controller validates
	// that the response parses as JSON before marking the step Succeeded.
	// Downstream steps can reference structured fields via "{{ .steps.<name>.data.<field> }}".
	OutputSchema string `json:"outputSchema,omitempty"`

	// If is an optional Go template expression. When set, the step only executes if the
	// expression evaluates to a truthy value. A falsy result marks the step Skipped, which
	// counts as satisfied for downstream dependency checks.
	// Example: "{{ .steps.check.data.shouldContinue }}"
	If string `json:"if,omitempty"`

	// Loop makes this step repeat until Condition evaluates to false or MaxIterations is reached.
	// Each successful iteration resets the step to Pending so it can be re-submitted.
	Loop *LoopSpec `json:"loop,omitempty"`
}

// ArkFlowSpec defines the desired state of ArkFlow.
type ArkFlowSpec struct {
	// Steps is the ordered (DAG) list of pipeline nodes.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	Steps []ArkFlowStep `json:"steps"`

	// Input is the initial data passed into the pipeline. Step inputs can
	// reference these values via "{{ .pipeline.input.<key> }}".
	Input map[string]string `json:"input,omitempty"`

	// Output is a Go template expression that selects the final pipeline result.
	// Example: "{{ .steps.summarize.output }}"
	Output string `json:"output,omitempty"`

	// TimeoutSeconds is the maximum wall-clock seconds the pipeline may run before being
	// failed with reason TimedOut. Zero means no timeout.
	// +kubebuilder:validation:Minimum=1
	TimeoutSeconds int `json:"timeoutSeconds,omitempty"`

	// MaxTokens is the total token budget (input + output) for the entire pipeline run.
	// The pipeline is failed with reason BudgetExceeded if this limit is reached.
	// Zero means no limit.
	// +kubebuilder:validation:Minimum=1
	MaxTokens int64 `json:"maxTokens,omitempty"`
}

// ArkFlowStepStatus captures the observed state of a single step.
type ArkFlowStepStatus struct {
	// Name matches the step name in spec.
	Name string `json:"name"`
	// Phase is the current execution phase.
	Phase ArkFlowStepPhase `json:"phase"`
	// TaskID is the Redis stream message ID of the submitted task, used to
	// correlate results from the agent-tasks-results stream.
	TaskID string `json:"taskID,omitempty"`
	// Output is the agent's raw text response once the step has succeeded.
	Output string `json:"output,omitempty"`

	// OutputJSON is the agent's response as a JSON string, populated when the step
	// has an OutputSchema and the response is valid JSON. Downstream steps can
	// reference fields via "{{ .steps.<name>.data.<field> }}".
	OutputJSON string `json:"outputJSON,omitempty"`
	// StartTime is when the step started executing.
	StartTime *metav1.Time `json:"startTime,omitempty"`
	// CompletionTime is when the step finished (success or failure).
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`
	// Message holds a human-readable status detail.
	Message string `json:"message,omitempty"`
	// Iterations is the number of times this step has been executed (for loop steps).
	Iterations int `json:"iterations,omitempty"`
	// TokenUsage reports the tokens consumed by this step's LLM calls.
	TokenUsage *TokenUsage `json:"tokenUsage,omitempty"`
}

// ArkFlowStatus defines the observed state of ArkFlow.
type ArkFlowStatus struct {
	// Phase is the overall pipeline execution state.
	Phase ArkFlowPhase `json:"phase,omitempty"`
	// Steps holds per-step status.
	Steps []ArkFlowStepStatus `json:"steps,omitempty"`
	// StartTime is when the pipeline started.
	StartTime *metav1.Time `json:"startTime,omitempty"`
	// CompletionTime is when the pipeline finished.
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`
	// Output is the resolved final pipeline output once phase is Succeeded.
	Output string `json:"output,omitempty"`
	// ObservedGeneration is the .metadata.generation this status reflects.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// TotalTokenUsage is the sum of token usage across all steps.
	TotalTokenUsage *TokenUsage `json:"totalTokenUsage,omitempty"`
	// Conditions reflect the current state of the ArkFlow.
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="In",type=integer,JSONPath=`.status.totalTokenUsage.inputTokens`,priority=0
// +kubebuilder:printcolumn:name="Out",type=integer,JSONPath=`.status.totalTokenUsage.outputTokens`,priority=0
// +kubebuilder:printcolumn:name="Tokens",type=integer,JSONPath=`.status.totalTokenUsage.totalTokens`
// +kubebuilder:printcolumn:name="Started",type=date,JSONPath=`.status.startTime`
// +kubebuilder:printcolumn:name="Completed",type=date,JSONPath=`.status.completionTime`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
// +kubebuilder:resource:scope=Namespaced

// ArkFlow defines a DAG of agent steps where outputs feed into inputs.
type ArkFlow struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +required
	Spec ArkFlowSpec `json:"spec"`

	// +optional
	Status ArkFlowStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ArkFlowList contains a list of ArkFlow.
type ArkFlowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ArkFlow `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ArkFlow{}, &ArkFlowList{})
}
